/*
--------------------------------------------------
Module Name : Configuration Engine
File Name   : config.js
Version     : 1.0
Author      : RK Quality Solutions
Purpose     : Central configuration - brand, theme, defaults, version
Dependencies: none
--------------------------------------------------
*/

const AppConfig = {

    APP_NAME: "RKQS Smart Quality Dashboard Suite",
    APP_VERSION: "2.0.0",

    // ---------------------------------------------------------
    // EDITION: "master" or "client"
    // Master Edition -> RK Quality Solutions branding + admin controls
    // Client Edition -> Client branding, no admin controls
    // ---------------------------------------------------------
    EDITION: "master",

    // ---------------------------------------------------------
    // BRANDING - this block is generated by the White Label Engine
    // when a client package is exported. Editing these values and
    // switching EDITION to "client" is exactly what Module-12
    // (White Label Engine) automates.
    // ---------------------------------------------------------
    BRANDING: {
        master: {
            companyName: "RK Quality Solutions",
            tagline: "SMART QUALITY DASHBOARD SUITE",
            logo: "assets/logos/rkqs_logo.png",
            dashboardLabel: "Master Dashboard",
            editionBadge: "Master Edition"
        },
        client: {
            companyName: "SHIVANI LOCKS PRIVATE LIMITED (UNIT-II)",
            tagline: "",
            logo: "assets/logos/client_logo.png",
            dashboardLabel: "Client Dashboard",
            editionBadge: "Client Edition"
        }
    },

    // ---------------------------------------------------------
    // THEME - color tokens consumed by variables.css at runtime
    // Theme Manager (Module-13) writes into this object.
    // ---------------------------------------------------------
    THEME: {
        master: {
            primary: "#12224A",     // deep navy (sidebar / brand)
            primaryLight: "#1B336B",
            accent: "#C9A227",      // gold accent (RKQS identity)
            accentSoft: "#F4E9C9",
            success: "#1E8E5A",
            warning: "#E0A100",
            danger: "#D64545",
            info: "#2F6FED",
            surface: "#FFFFFF",
            surfaceAlt: "#F5F7FB",
            border: "#E4E8F0",
            textPrimary: "#16213A",
            textSecondary: "#64708A"
        },
        client: {
            primary: "#0B2E4E",     // client theme can be re-colored per package
            primaryLight: "#123F69",
            accent: "#1E9E8C",
            accentSoft: "#D9F2EF",
            success: "#1E8E5A",
            warning: "#E0A100",
            danger: "#D64545",
            info: "#2F6FED",
            surface: "#FFFFFF",
            surfaceAlt: "#F5F7FB",
            border: "#E4E8F0",
            textPrimary: "#16213A",
            textSecondary: "#64708A"
        }
    },

    // ---------------------------------------------------------
    // DEFAULT SETTINGS
    // ---------------------------------------------------------
    DEFAULTS: {
        dateFormat: "DD-MMM-YYYY",
        defectThresholdPercent: 8,      // used for alert generation
        fpyThresholdPercent: 90,
        inspectionCoverageThreshold: 90,
        chartAnimationMs: 600,
        currency: "INR",
        largeDatasetRowThreshold: 3000   // above this row count, chart animation auto-disables (SRS 18.1/18.2)
    },

    // ---------------------------------------------------------
    // REQUIRED EXCEL COLUMNS (Section 7.1 of SRS) - the Validation
    // Engine and Excel Engine both read from this single source.
    // ---------------------------------------------------------
    REQUIRED_COLUMNS: [
        { key: "date",        label: "Date",             mandatory: true },
        { key: "plant",       label: "Plant",             mandatory: true },
        { key: "department",  label: "Department",        mandatory: true },
        { key: "process",     label: "Process",           mandatory: true },
        { key: "line",        label: "Production line",   mandatory: true },
        { key: "shift",       label: "Shift",             mandatory: true },
        { key: "customer",    label: "Customer",          mandatory: true },
        { key: "partNo",      label: "Part No",           mandatory: true },
        { key: "partName",    label: "Part Name",         mandatory: true },
        { key: "operator",    label: "Operator",          mandatory: false },
        { key: "inspector",   label: "Inspector",         mandatory: false },
        { key: "productionQty", label: "Production Qty",  mandatory: true },
        { key: "inspectionQty", label: "Inspection Qty",  mandatory: true },
        { key: "defectName",  label: "Defect Name",       mandatory: true },
        { key: "defectQty",   label: "Defect Qty",        mandatory: true },
        { key: "disposition", label: "Disposition",       mandatory: true },
        { key: "remarks",     label: "Remarks",           mandatory: false }
    ],

    // Chart color palette (used by Chart Engine so every chart is consistent)
    CHART_PALETTE: [
        "#12224A", "#2F6FED", "#C9A227", "#1E8E5A", "#D64545",
        "#7C4DFF", "#00B8D9", "#E0A100", "#6B7C93", "#9C27B0"
    ],

    // ---------------------------------------------------------
    // THEME PRESETS - Theme Manager (Module-13, Master only) lets the
    // admin pick one of these and toggle light/dark mode. Selecting a
    // preset overwrites AppConfig.THEME[edition] primary/accent colors.
    // ---------------------------------------------------------
    THEME_PRESETS: [
        { key: "navyGold", name: "Navy & Gold", primary: "#12224A", primaryLight: "#1B336B", accent: "#C9A227", accentSoft: "#F4E9C9" },
        { key: "deepSpace", name: "Deep Space Multicolor", primary: "#151B3D", primaryLight: "#232A5C", accent: "#00D4FF", accentSoft: "#173042" },
        { key: "oceanTeal", name: "Ocean Teal", primary: "#0B2E4E", primaryLight: "#123F69", accent: "#1E9E8C", accentSoft: "#D9F2EF" },
        { key: "charcoalCrimson", name: "Charcoal Crimson", primary: "#22262E", primaryLight: "#333944", accent: "#D6455B", accentSoft: "#F6D9DE" },
        { key: "slatePurple", name: "Slate Purple", primary: "#2B2545", primaryLight: "#413A6B", accent: "#8B6BD8", accentSoft: "#E7E0FA" },
        { key: "forestGreen", name: "Forest Green", primary: "#173B2C", primaryLight: "#245240", accent: "#3FA66B", accentSoft: "#D8F0E1" }
    ],

    // Default UI mode ("light" or "dark"), overridden by Theme Manager
    UI_MODE: "light"
};

// Convenience getter - always resolve branding/theme for the *current* edition
function getActiveBranding() {
    return AppConfig.BRANDING[AppConfig.EDITION];
}
function getActiveTheme() {
    return AppConfig.THEME[AppConfig.EDITION];
}
